spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password: cGFzc3dvcmQxMjMK
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
    default-schema: trade
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/eco-trade?currentSchema=trade
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 16MB
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: false
server:
  servlet:
    context-path: /api/trade
  port: 8080
security:
  basic:
    enable: false
secret:
  key: 7BC3D39388C9B
  time: 180000000
aws:
  region: us-east-1
  bucketName: eco-trade
  key: <SUA KEY AQUI>
  secret: <SEU SECRET AQUI>
ecotrade:
  ecopoints:
    quantity: 300