spring:
  cache:
    type: redis
  redis:
    host: ${REDIS_URL}
    port: 6379
    password: ${REDIS_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
    default-schema: ${DEFAULT_SCHEMA}
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URL}:5432/${DB_DATABASE}?currentSchema=${DEFAULT_SCHEMA}
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 16MB
server:
  servlet:
    context-path: /api/trade
  port: 8080
security:
  basic:
    enable: false
secret:
  key: ${SECRET_KEY}
  time: 180000000
aws:
  region: ${BUCKET_REGION}
  bucketName: ${BUCKET_NAME}
  key: ${BUCKET_KEY}
  secret: ${BUCKET_SECRET}
ecotrade:
  ecopoints:
    quantity: ${ECO_POINTS_QUANTITY}